// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhUYktjVI3EKpUtEmXhyFLjcdiZpRTYm4',
    appId: '1:663934942595:web:d68f44b70231977fb74ab6',
    messagingSenderId: '663934942595',
    projectId: 'patient-app-2c555',
    authDomain: 'patient-app-2c555.firebaseapp.com',
    databaseURL: 'https://patient-app-2c555-default-rtdb.firebaseio.com',
    storageBucket: 'patient-app-2c555.appspot.com',
    measurementId: 'G-E8MT8Q14SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpjmCDbPUt-jHOOyy_oEEhOktim_RMAxA',
    appId: '1:663934942595:android:b1e5199d401b97dbb74ab6',
    messagingSenderId: '663934942595',
    projectId: 'patient-app-2c555',
    databaseURL: 'https://patient-app-2c555-default-rtdb.firebaseio.com',
    storageBucket: 'patient-app-2c555.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMBXkIoUc5Cs_74X_8384mYmULzTYKXN8',
    appId: '1:663934942595:ios:ce0eb416fe36f5cfb74ab6',
    messagingSenderId: '663934942595',
    projectId: 'patient-app-2c555',
    databaseURL: 'https://patient-app-2c555-default-rtdb.firebaseio.com',
    storageBucket: 'patient-app-2c555.appspot.com',
    iosClientId: '663934942595-af2teik6um7inedjvk1rhc2jio5s2jiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMBXkIoUc5Cs_74X_8384mYmULzTYKXN8',
    appId: '1:663934942595:ios:ce0eb416fe36f5cfb74ab6',
    messagingSenderId: '663934942595',
    projectId: 'patient-app-2c555',
    databaseURL: 'https://patient-app-2c555-default-rtdb.firebaseio.com',
    storageBucket: 'patient-app-2c555.appspot.com',
    iosClientId: '663934942595-af2teik6um7inedjvk1rhc2jio5s2jiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorApp',
  );
}
